"""THS-0003."""
class ThresholdError(Exception): ...
class ValidationError(ThresholdError): ...
class DataError(ThresholdError): ...
class ConfigError(ThresholdError): ...
class AdapterError(ThresholdError): ...
